openapi: 3.0.0
info:
  title: MktplaceApp APIs
  version: 1.0.0
  description: APIs for the marketplace application for buying and selling gaming assets

servers:
  - url: http://localhost:8080/api/v1

paths:
  /users/{userId}:
    get:
      operationId: getUserById
      summary: Get user details by Id
      tags:
        - User
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: String
          description: ID of the user to retrieve
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Internal server error

  /users:
    post:
      operationId: createUser
      summary: Create a new user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreationRequest'
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreationResponse'
        '500':
          description: Internal server error

  /users/{userId}/products:
    get:
      operationId: getAllProductsListedByUser
      summary: Get all products listed by a user
      tags:
        - User
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: String
          description: ID of the user to retrieve product listings for
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Internal server error

  /products:
    get:
      operationId: getAllProducts
      summary: Get all products
      tags:
        - Product
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Internal server error

    post:
      operationId: createProduct
      summary: Create a new product
      tags:
        - Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreationRequest'
      responses:
        '200':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCreationResponse'
        '500':
          description: Internal server error

  /products/{productId}:
    get:
      operationId: getProductById
      summary: Get a product by Id
      tags:
        - Product
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: integer
            format: int64
          description: ID of the product to retrieve
      responses:
        '200':
          description: product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
        '500':
          description: Internal server error

  /transactions:
    get:
      summary: Get all transactions
      responses:
        '200':
          description: A list of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'

    post:
      summary: Create a new transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          description: Transaction created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'

components:
  schemas:
    UserCreationRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 1
          maxLength: 50
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
          maxLength: 20
          pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$"
      required:
        - username
        - email
        - password

    UserCreationResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - success
            - failure
        user:
          $ref: '#/components/schemas/User'
          description: The created user object

    ProductCreationRequest:
      type: object
      properties:
        user_id:
          type: string
          minLength: 1
          maxLength: 50
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          minLength: 1
          maxLength: 500
        base_price:
          type: number
          format: double
        quantity_available:
          type: integer
          format: int64
      required:
        - user_id
        - name
        - description
        - base_price
        - quantity_available

    ProductCreationResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - success
            - failure
        user:
          $ref: '#/components/schemas/Product'
          description: The created product object

    User:
      type: object
      properties:
        id:
          type: String
          minLength: 1
          maxLength: 50
        username:
          type: string
          minLength: 1  # Minimum length of username
          maxLength: 50 # Maximum length of username
        email:
          type: string
          format: email  # Format validation for email
        password:
          type: string
          format: password
          readOnly: true
          minLength: 8   # Minimum length of password
          maxLength: 20  # Maximum length of password
          pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$"  # Password pattern (at least one lowercase, one uppercase, one digit)
        createdAt:
          type: integer
          format: int64
        updatedAt:
          type: integer
          format: int64

    Product:
      type: object
      properties:
        product_id:
          type: integer
          format: int64
        user_id:
          type: string
          minLength: 1
          maxLength: 50
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          minLength: 1
          maxLength: 500
        base_price:
          type: number
          format: double
        quantity_available:
          type: integer
          format: int64
        createdAt:
          type: integer
          format: int64
        updatedAt:
          type: integer
          format: int64

    Transaction:
      type: object
      properties:
        id:
          type: integer
          format: int64
        buyerId:
          type: integer
          format: int64
        itemId:
          type: integer
          format: int64
        price:
          type: number
          format: double
        transactionDate:
          type: integer
          format: int64
